### ISSUE TITLE
Pdfbook: Table of Contents links broken

### ISSUE THREAD

**Issue by stanlane** [OrganicDesign/extensions#27]
The **Table of Contents** links do not work in the browser nor in a PDF viewer.

**Comment by Aranad** [comment]
Are you using the most up-to-date version of the extension and of HTMLDOC? The links are working fine with current versions.

**Comment by Aranad** [comment]
Correction: the TOC links are only working in Firefox it seems. There is something different about the TOC links than other links in the page causing them to fail in external viewers and Chrome (and probably some other browsers). I'll see if I can see what's going on...

**Comment by stanlane** [comment]
* I downloaded https://github.com/OrganicDesign/extensions/tarball/master, extracted it, and placed OrganicDesign-extensions-49a9f8e/MediaWiki/PdfBook in ~/mediawiki-1.28.2-0/apps/mediawiki/htdocs/extensions/
* I added ```wfLoadExtension( 'PdfBook' );``` to LocalSettings.php
* I have run: sudo apt-get install htmldoc

This works but not the TOC (not even in Firefox ESR 52.0.2):
> http://localhost:8080/mediawiki/index.php?title=Category:Test&action=pdfbook

It is very important that the links works in Firefox ESR because GNU IceCat is based on it. IceCat is ethical superior.

**Comment by stanlane** [comment]
@Aranad * I downloaded https://github.com/OrganicDesign/extensions/tarball/master, extracted it, and placed OrganicDesign-extensions-49a9f8e/MediaWiki/PdfBook in ~/mediawiki-1.28.2-0/apps/mediawiki/htdocs/extensions/
* I added ```wfLoadExtension( 'PdfBook' );``` to LocalSettings.php
* I have run: sudo apt-get install htmldoc

This works but not the TOC (not even in Firefox ESR 52.0.2):
> http://localhost:8080/mediawiki/index.php?title=Category:Test&action=pdfbook

It is very important that the links works in Firefox ESR because GNU IceCat is based on it. IceCat is ethical superior.

**Comment by stanlane** [comment]
@Aranad The TOC didn't work with ther regular of Firefox version for GNU/Linux either: https://ftp.mozilla.org/pub/firefox/releases/52.0.2/linux-x86_64/en-US/firefox-52.0.2.tar.bz2

**Comment by stanlane** [comment]
@Aranad Can you please add appropriate labels to this issue?

**Comment by Aranad** [comment]
I just fixed this now and bumped the version to 1.5.1. The problem was that MediaWiki wasn't using old-style <a name="target"> tags to match the TOC link's #target which HTMLDOC needs for them to work properly.

**Comment by stanlane** [comment]
@Aranad Thank you for caring about this. 1.5.1, 2017-05-14 didn't work though.

**Comment by Aranad** [comment]
Try editing the article that you are testing to ensure that you're not getting a cached version.. here's an example from my site which is running the current version:
https://www.organicdesign.co.nz/wiki/index.php?title=Security&action=pdfbook&format=single

**Comment by davidhedlund** [comment]
@Aranad 

* Your link also works for me, good! Do you use **PdfBook 1.5.1, 2017-05-14**?

* I'm still stuck, editing the article didn't help. However, I need to use http://localhost:8080/mediawiki/index.php?title=Category:Test&action=pdfbook and that cover many articles so I need to empty the cache for the whole MediaWiki instance. Restarting Apache and MySQL didn't help.

Can you please help me?

**Comment by stanlane** [comment]
@Aranad 

* Your link also works for me, good! Do you use **PdfBook 1.5.1, 2017-05-14**?

* I'm still stuck, editing the article didn't help. However, I need to use http://localhost:8080/mediawiki/index.php?title=Category:Test&action=pdfbook and that cover many articles so I need to empty the cache for the whole MediaWiki instance. Restarting Apache and MySQL didn't help.

Can you please help me?

**Comment by stanlane** [comment]
@Aranad 
This didn't help
>php/bin/php apps/mediawiki/htdocs/maintenance/purgeList.php --purge --all

**Comment by Aranad** [comment]
The purge only clears caches that are in the wiki itself, but the pdf book cached data is in files. The cache key is based on the article title and the article content so even if you upgrade the pdfbook code, the pdf output will remain the same if the content of the rendered article is unchanged. The cached pdf files are in your ```$wgUploadDirectory``` and have a ```pdf-book-cache-``` filename prefix, so you can manually delete then to ensure the pdf your seeing is definitely being rendered by the updated code.

**Comment by Aranad** [comment]
Incidentally I just committed another version (1.5.2) which includes the script itself in the hash that is used as the cache key, this way cached files that were made by older code will never be used.

**Comment by stanlane** [comment]
@Aranad 
>Incidentally I just committed another version (1.5.2) which includes the script itself in the hash that is used as the cache key, this way cached files that were made by older code will never be used.

Please open a separate issue for this and add 1) a commit link in that issue 2) link that issue to this one.

**Comment by stanlane** [comment]
@Aranad Can you please also add a commit link to https://github.com/OrganicDesign/extensions/issues/27#issuecomment-301338942 ?

**Comment by stanlane** [comment]
@Aranad Still doesn't work in **PdfBook 1.5.2, 2017-05-15** after
* php/bin/php apps/mediawiki/htdocs/maintenance/purgeList.php --purge --all
* Restarted Apache MySQL

**Comment by Aranad** [comment]
It's a mystery, it's working on some wikis and not others but I can't see any difference in the output being passed to HTMLDOC... I'll have to have a think about it some more...

**Comment by Aranad** [comment]
The problem seems to be something to do with local installations... I've tested on a number of mediawiki versions ranging from 1.21 to 1.28 on my server and TOC links are working for all. But TOC links are failing on pdfs generated from a mediawiki 1.28 running locally.

**Comment by Aranad** [comment]
aha! there's broken html being sent into HTMLDOC on the failing ones....
e.g. ```<h2><a name="foo"><span class="mw-headline-number">1</a> foo</span></h2>```
Should have it sorted soon :-)

**Comment by Aranad** [comment]
Nope :( unfortunately that was a red herring, some of the ones with good html have non-working TOC links and visa versa. I can't see any reason why some are not working. It's going to have to go into the too-hard basket for now sorry :-(

**Comment by stanlane** [comment]
@Aranad Thank you for trying to fix this. Can you please ask someone else look at it too?

**Comment by stanlane** [comment]
@Aranad Can you please install the out of the box solution Bitnami MediaWiki Stack for GNU/Linux: https://bitnami.com/stack/mediawiki/installer#linux

**Comment by Aranad** [comment]
I don't have any more time available for this t the moment sorry, I'll have another look in a week or so.

**Comment by stanlane** [comment]
@Aranad I understand. Thank you for taking your time.

**Comment by stanlane** [comment]
@Aranad You can get older Bitnami MediaWiki versions here:
* https://downloads.bitnami.com/files/stacks/mediawiki/1.27.1-1/bitnami-mediawiki-1.27.1-1-linux-x64-installer.run
* https://downloads.bitnami.com/files/stacks/mediawiki/1.28.0-0/bitnami-mediawiki-1.28.0-0-linux-x64-installer.run

**Comment by Aranad** [comment]
I won't be installing bitnami, I already have my own MW installations and procedures in place.

**Comment by stanlane** [comment]
@Aranad Please let me know when you have re-evaluated this issue.

**Comment by Aranad** [comment]
I think this one's going to have to go in the too-hard basket for now, I'm back but I have too much on to look in to it.

**Comment by stanlane** [comment]
@Aranad Can someone else work on this then?

**Comment by Aranad** [comment]
Sure if anyone finds a solution, I'll be happy to merge it into the code.
